/**
 * migrate.js — Auto-create tables on startup
 * เรียก runMigrations() ตอน server start → สร้างตารางถ้ายังไม่มี
 */

const db = require('./db');

async function runMigrations() {
    console.log('🔄 [Migrate] Running database migrations...');
    
    try {
        // ══════════════════════════════════════════
        // Core ERP Tables
        // ══════════════════════════════════════════
        
        await db.query(`
            CREATE TABLE IF NOT EXISTS employee (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                role TEXT NOT NULL
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS customer (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                contact_person TEXT,
                credit_limit REAL DEFAULT 0,
                phone TEXT,
                customer_type TEXT DEFAULT 'B2B',
                balance REAL DEFAULT 0
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS product (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                type TEXT NOT NULL,
                base_price REAL NOT NULL
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS job_order (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id BIGINT REFERENCES customer(id),
                product_id BIGINT REFERENCES product(id),
                quantity BIGINT,
                total_price REAL,
                status TEXT DEFAULT 'pending',
                production_stage TEXT DEFAULT 'planning',
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS lead_contact (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                line_user_id TEXT,
                fb_user_id TEXT,
                platform TEXT DEFAULT 'line',
                original_name TEXT,
                avatar_url TEXT,
                erp_alias_name TEXT,
                tags JSONB DEFAULT '[]'::jsonb,
                sales_status TEXT DEFAULT 'i',
                customer_id BIGINT REFERENCES customer(id),
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        // Unique index on line_user_id (allow nulls)
        await db.query(`
            CREATE UNIQUE INDEX IF NOT EXISTS idx_lead_line_user ON lead_contact(line_user_id) WHERE line_user_id IS NOT NULL;
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS chat_message (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id BIGINT REFERENCES lead_contact(id),
                sender TEXT NOT NULL,
                type TEXT NOT NULL,
                text_content TEXT,
                media_url TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS knowledge_base (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question TEXT,
                answer TEXT,
                category TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        // ══════════════════════════════════════════
        // Production Tables
        // ══════════════════════════════════════════
        
        await db.query(`
            CREATE TABLE IF NOT EXISTS production_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_order_id BIGINT REFERENCES job_order(id),
                employee_id BIGINT REFERENCES employee(id),
                process_name TEXT NOT NULL,
                sub_process TEXT,
                status TEXT DEFAULT 'in_progress',
                started_at TIMESTAMPTZ DEFAULT NOW(),
                completed_at TIMESTAMPTZ,
                notes TEXT
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS logistics_trips (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_order_id BIGINT,
                driver TEXT,
                vehicle TEXT,
                destination TEXT,
                status TEXT DEFAULT 'planned',
                planned_date TIMESTAMPTZ,
                actual_departure TIMESTAMPTZ,
                actual_arrival TIMESTAMPTZ,
                notes TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        // ══════════════════════════════════════════
        // AI Agent Reports
        // ══════════════════════════════════════════
        
        await db.query(`
            CREATE TABLE IF NOT EXISTS agent_reports (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                report_type TEXT NOT NULL,
                reporter_name TEXT NOT NULL,
                reporter_role TEXT,
                reporter_line_id TEXT,
                group_name TEXT,
                group_id TEXT,
                title TEXT,
                content TEXT NOT NULL,
                raw_message TEXT,
                status TEXT DEFAULT 'logged',
                priority TEXT DEFAULT 'normal',
                assigned_to TEXT,
                resolved_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`CREATE INDEX IF NOT EXISTS idx_reports_type ON agent_reports(report_type);`);
        await db.query(`CREATE INDEX IF NOT EXISTS idx_reports_reporter ON agent_reports(reporter_line_id);`);
        await db.query(`CREATE INDEX IF NOT EXISTS idx_reports_status ON agent_reports(status);`);
        await db.query(`CREATE INDEX IF NOT EXISTS idx_reports_created ON agent_reports(created_at DESC);`);

        // ══════════════════════════════════════════
        // Time Logger / HR Tables
        // ══════════════════════════════════════════

        await db.query(`
            CREATE TABLE IF NOT EXISTS time_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_id BIGINT REFERENCES employee(id),
                job_order_id BIGINT,
                process_name TEXT,
                sub_process TEXT,
                start_time TIMESTAMPTZ DEFAULT NOW(),
                end_time TIMESTAMPTZ,
                duration_minutes REAL,
                notes TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        console.log('✅ [Migrate] All tables ready!');
        return true;
    } catch (e) {
        console.error('❌ [Migrate] Error:', e.message);
        return false;
    }
}

module.exports = { runMigrations };
