/**
 * migrate.js — Auto-create tables on startup
 * เรียก runMigrations() ตอน server start → สร้างตารางถ้ายังไม่มี
 */

const db = require('./db');

async function runMigrations() {
    console.log('🔄 [Migrate] Running database migrations...');
    
    try {
        // ══════════════════════════════════════════
        // Core ERP Tables
        // ══════════════════════════════════════════
        
        await db.query(`
            CREATE TABLE IF NOT EXISTS erp_users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                pin_code TEXT NOT NULL,
                full_name TEXT,
                role TEXT DEFAULT 'Operator',
                active BOOLEAN DEFAULT true,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS employee (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                role TEXT NOT NULL
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS customer (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                contact_person TEXT,
                credit_limit REAL DEFAULT 0,
                phone TEXT,
                customer_type TEXT DEFAULT 'B2B',
                balance REAL DEFAULT 0
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS product (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                type TEXT NOT NULL,
                base_price REAL NOT NULL
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS job_order (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id BIGINT REFERENCES customer(id),
                product_id BIGINT REFERENCES product(id),
                quantity BIGINT,
                total_price REAL,
                status TEXT DEFAULT 'pending',
                production_stage TEXT DEFAULT 'planning',
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS lead_contact (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                line_user_id TEXT,
                fb_user_id TEXT,
                platform TEXT DEFAULT 'line',
                original_name TEXT,
                avatar_url TEXT,
                erp_alias_name TEXT,
                tags JSONB DEFAULT '[]'::jsonb,
                sales_status TEXT DEFAULT 'i',
                customer_id BIGINT REFERENCES customer(id),
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        // Unique index on line_user_id (allow nulls)
        await db.query(`
            CREATE UNIQUE INDEX IF NOT EXISTS idx_lead_line_user ON lead_contact(line_user_id) WHERE line_user_id IS NOT NULL;
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS chat_message (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id BIGINT REFERENCES lead_contact(id),
                sender TEXT NOT NULL,
                type TEXT NOT NULL,
                text_content TEXT,
                media_url TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS knowledge_base (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question TEXT,
                answer TEXT,
                category TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        // ══════════════════════════════════════════
        // Production Tables
        // ══════════════════════════════════════════
        
        await db.query(`
            CREATE TABLE IF NOT EXISTS production_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_order_id BIGINT REFERENCES job_order(id),
                employee_id BIGINT REFERENCES employee(id),
                process_name TEXT NOT NULL,
                sub_process TEXT,
                status TEXT DEFAULT 'in_progress',
                started_at TIMESTAMPTZ DEFAULT NOW(),
                completed_at TIMESTAMPTZ,
                notes TEXT
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS logistics_trips (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_order_id BIGINT,
                driver TEXT,
                vehicle TEXT,
                destination TEXT,
                status TEXT DEFAULT 'planned',
                planned_date TIMESTAMPTZ,
                actual_departure TIMESTAMPTZ,
                actual_arrival TIMESTAMPTZ,
                notes TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        // ══════════════════════════════════════════
        // AI Agent Reports
        // ══════════════════════════════════════════
        
        await db.query(`
            CREATE TABLE IF NOT EXISTS agent_reports (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                report_type TEXT NOT NULL,
                reporter_name TEXT NOT NULL,
                reporter_role TEXT,
                reporter_line_id TEXT,
                group_name TEXT,
                group_id TEXT,
                title TEXT,
                content TEXT NOT NULL,
                raw_message TEXT,
                status TEXT DEFAULT 'logged',
                priority TEXT DEFAULT 'normal',
                assigned_to TEXT,
                resolved_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`CREATE INDEX IF NOT EXISTS idx_reports_type ON agent_reports(report_type);`);
        await db.query(`CREATE INDEX IF NOT EXISTS idx_reports_reporter ON agent_reports(reporter_line_id);`);
        await db.query(`CREATE INDEX IF NOT EXISTS idx_reports_status ON agent_reports(status);`);
        await db.query(`CREATE INDEX IF NOT EXISTS idx_reports_created ON agent_reports(created_at DESC);`);

        // ══════════════════════════════════════════
        // Time Logger / HR Tables
        // ══════════════════════════════════════════

        await db.query(`
            CREATE TABLE IF NOT EXISTS time_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_id BIGINT REFERENCES employee(id),
                job_order_id BIGINT,
                process_name TEXT,
                sub_process TEXT,
                start_time TIMESTAMPTZ DEFAULT NOW(),
                end_time TIMESTAMPTZ,
                duration_minutes REAL,
                notes TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        // ══════════════════════════════════════════
        // Team Members (LINE self-registration)
        // ══════════════════════════════════════════

        await db.query(`
            CREATE TABLE IF NOT EXISTS team_members (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                line_user_id TEXT UNIQUE NOT NULL,
                name TEXT NOT NULL,
                role TEXT DEFAULT 'Operator',
                access TEXT DEFAULT 'production',
                status TEXT DEFAULT 'pending',
                registered_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);
        await db.query(`CREATE UNIQUE INDEX IF NOT EXISTS idx_tm_line ON team_members(line_user_id);`);

        // ══════════════════════════════════════════
        // Smart Factory — APS / MES Tables
        // ══════════════════════════════════════════

        await db.query(`
            CREATE TABLE IF NOT EXISTS work_centers (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                type TEXT DEFAULT 'general',
                capacity_per_hour REAL DEFAULT 0,
                shift_hours REAL DEFAULT 8,
                status TEXT DEFAULT 'active',
                notes TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS production_schedule (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_order_id BIGINT,
                work_center_id BIGINT,
                job_name TEXT,
                customer_name TEXT,
                quantity INTEGER DEFAULT 0,
                scheduled_start TIMESTAMPTZ,
                scheduled_end TIMESTAMPTZ,
                actual_start TIMESTAMPTZ,
                actual_end TIMESTAMPTZ,
                status TEXT DEFAULT 'queued',
                priority INTEGER DEFAULT 5,
                sequence_order INTEGER DEFAULT 0,
                estimated_duration_min INTEGER DEFAULT 60,
                is_urgent BOOLEAN DEFAULT FALSE,
                urgent_approved_by TEXT,
                urgent_reason TEXT,
                stage TEXT DEFAULT 'planning',
                notes TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`CREATE INDEX IF NOT EXISTS idx_ps_status ON production_schedule(status);`);
        await db.query(`CREATE INDEX IF NOT EXISTS idx_ps_wc ON production_schedule(work_center_id);`);
        await db.query(`CREATE INDEX IF NOT EXISTS idx_ps_start ON production_schedule(scheduled_start);`);

        await db.query(`
            CREATE TABLE IF NOT EXISTS oee_records (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                work_center_id BIGINT,
                record_date DATE,
                planned_time_min REAL DEFAULT 0,
                actual_run_time_min REAL DEFAULT 0,
                downtime_min REAL DEFAULT 0,
                ideal_cycle_time REAL DEFAULT 0,
                total_produced INTEGER DEFAULT 0,
                good_produced INTEGER DEFAULT 0,
                defects INTEGER DEFAULT 0,
                availability REAL DEFAULT 0,
                performance REAL DEFAULT 0,
                quality REAL DEFAULT 0,
                oee REAL DEFAULT 0,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS changeover_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                work_center_id BIGINT,
                from_job TEXT,
                to_job TEXT,
                start_time TIMESTAMPTZ,
                end_time TIMESTAMPTZ,
                duration_min REAL DEFAULT 0,
                notes TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        await db.query(`
            CREATE TABLE IF NOT EXISTS capacity_calendar (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                work_center_id BIGINT,
                calendar_date DATE,
                shift TEXT DEFAULT 'day',
                available_hours REAL DEFAULT 8,
                booked_hours REAL DEFAULT 0,
                utilization_pct REAL DEFAULT 0,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);

        console.log('✅ [Migrate] All tables ready (including Smart Factory)!');
        return true;
    } catch (e) {
        console.error('❌ [Migrate] Error:', e.message);
        return false;
    }
}

module.exports = { runMigrations };
