-- ══════════════════════════════════════════════════════
-- BookBox AI Agent — ตารางรายงาน (ใช้ได้จริง)
-- ══════════════════════════════════════════════════════
-- ก๊อปทั้งหมดนี้ไปวางใน Supabase SQL Editor แล้วกด RUN
-- ══════════════════════════════════════════════════════

-- ตารางรายงานหลัก (รองรับทุกประเภท)
CREATE TABLE IF NOT EXISTS agent_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type TEXT NOT NULL,          -- 'work_log', 'nc', 'sales', 'delivery', 'transfer', 'general'
    reporter_name TEXT NOT NULL,        -- ชื่อคนรายงาน (จาก whitelist)
    reporter_role TEXT,                 -- บทบาท (IT, HR, ผจก. ฯลฯ)
    reporter_line_id TEXT,              -- LINE User ID
    group_name TEXT,                    -- ชื่อห้อง LINE (ถ้ามี)
    group_id TEXT,                      -- Group ID (ถ้ามี)
    title TEXT,                         -- หัวข้อรายงาน
    content TEXT NOT NULL,              -- เนื้อหารายงาน
    raw_message TEXT,                   -- ข้อความต้นฉบับที่พิมพ์มา
    status TEXT DEFAULT 'logged',       -- 'logged', 'in_progress', 'resolved', 'approved'
    priority TEXT DEFAULT 'normal',     -- 'low', 'normal', 'high', 'urgent'
    assigned_to TEXT,                   -- มอบหมายให้ใคร
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index สำหรับค้นหาเร็ว
CREATE INDEX IF NOT EXISTS idx_reports_type ON agent_reports(report_type);
CREATE INDEX IF NOT EXISTS idx_reports_reporter ON agent_reports(reporter_line_id);
CREATE INDEX IF NOT EXISTS idx_reports_status ON agent_reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_created ON agent_reports(created_at DESC);

-- ═══ เปิดสิทธิ์ให้ backend เข้าถึงได้ ═══
ALTER TABLE agent_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for service role" ON agent_reports
    FOR ALL USING (true) WITH CHECK (true);
